#!/usr/bin/env python3
"""
resibox bulk-config generator — scale to hundreds/thousands of containers.

Inputs (files next to this script, one entry per line):
  accounts.txt   email:pass        (honeygain AND pawns accept same creds format)
  proxies.txt    full proxy URL with a literal 'sid-' placeholder OR fixed sid
                 e.g. http://res-fr-sid-RANDOM:KEY@gw.proxyrise.com:443
                 'RANDOM' is replaced by a unique sticky id per container.
  countries.txt  optional ISO codes cycled per container (GB, FR, DE, ...)

Usage:
  python3 gen-config.py --count 200 --out config-200.toml
  python3 gen-config.py --count 50 --apps hg-only --out small.toml
"""
import argparse, random, pathlib

HERE = pathlib.Path(__file__).parent

def load(fname):
    p = HERE / fname
    if not p.exists():
        return []
    return [l.strip() for l in p.read_text().splitlines() if l.strip() and not l.startswith("#")]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=10)
    ap.add_argument("--accounts", default="accounts.txt")
    ap.add_argument("--proxies", default="proxies.txt")
    ap.add_argument("--countries", default="countries.txt")
    ap.add_argument("--out", default="config-generated.toml")
    ap.add_argument("--stagger", type=int, default=5,
                    help="seconds between container startups")
    ap.add_argument("--per-account-devices", type=int, default=8,
                    help="max devices per account (honeygain limit ~10)")
    args = ap.parse_args()

    accounts = load(args.accounts)
    proxies = load(args.proxies)
    countries = load(args.countries)
    if not accounts or not proxies:
        raise SystemExit(f"need {args.accounts} and {args.proxies}")

    # account pool: cycle but cap devices/account
    max_use = args.per_account_devices
    acct_pool = []
    while len(acct_pool) < args.count:
        for a in accounts:
            acct_pool.extend([a] * min(max_use, args.count - len(acct_pool)))
            if len(acct_pool) >= args.count:
                break

    lines = ["""# AUTO-GENERATED by gen-config.py — do not hand-edit
[general]
health_port = 8080
verify_interval_secs = 90
enforcement = "userspace"
startup_stagger_secs = %d
max_consecutive_failures = 3
verify_urls = ["https://api.ipquery.io/?format=json", "https://ipwho.is/"]
""" % args.stagger]

    for i in range(args.count):
        email, pwd = acct_pool[i].split(":", 1)
        proxy_tpl = random.choice(proxies)
        proxy = proxy_tpl.replace("RANDOM", str(random.randint(100000000, 999999999)))
        cc = countries[i % len(countries)] if countries else ""
        name = f"c{i:04d}-{cc.lower() or 'xx'}"
        lines.append(f"""
[[container]]
name = "{name}"
proxy = "{proxy}"
expected_country = "{cc}"
hg_cmd = ["bin/honeygain", "-email", "{email}", "-pass", "{pwd}", "-device", "HG-{name}", "-tou-accept"]
pawns_cmd = ["bin/pawns-cli", "-email={email}", "-password={pwd}", "-device-name=PB-{name}", "-accept-tos"]
""")

    out = HERE / args.out
    out.write_text("".join(lines))
    print(f"wrote {args.count} containers -> {out}")
    print(f"accounts used: {min(len(accounts) * max_use, args.count)} slots from {len(accounts)} accounts")

if __name__ == "__main__":
    main()
